import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { Amplify } from 'aws-amplify';
import { withAuthenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import { Stack } from '@mui/system';
import {
  Box,
  Button,
  Container,
  Divider,
  Drawer,
  Grid,
  Link,
  List,
  ListItem,
  ListItemButton,
  ListItemText,
  useMediaQuery,
} from '@mui/material';
import MenuIcon from '@mui/icons-material/Menu';
import { useState } from 'react';

// import awsExports from '../aws-exports';
// Amplify.configure(awsExports);

const inter = Inter({ subsets: ['latin'] });

// function Home({ signOut, user }) {
function Home() {
  const matches = useMediaQuery('(min-width:996px)');
  const [isOpenDrawer, setDrawerState] = useState(false);

  return (
    <>
      <Head>
        <title>マッチングアプリ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <header>
          <Stack
            direction="row"
            alignItems="center"
            justifyContent="space-between"
            sx={{ height: 50 }}
          >
            <Stack
              direction="row"
              alignItems="center"
              justifyContent="center"
              spacing={2}
            >
              {matches ? (
                <>
                  <Image
                    src="/images/site_logo.png"
                    width={271}
                    height={48}
                    alt="Site Logo"
                  />
                  <Link href="#" underline="always" color="inherit">
                    上越市に移住したい
                  </Link>
                  <Link href="#" underline="always" color="inherit">
                    上越市を紹介したい
                  </Link>
                </>
              ) : (
                <Image
                  src="/images/site_logo.png"
                  width={203}
                  height={36}
                  alt="Site Logo"
                />
              )}
            </Stack>
            <Stack
              direction="row"
              alignItems="center"
              justifyContent="center"
              spacing={2}
            >
              {/* {user ? (
                <Button variant="text">サインアウト</Button>
              ) : (
                <Button variant="text">サインイン</Button>
              )} */}
              {matches ? (
                <>
                  <Button variant="text">サインイン</Button>
                  <Button variant="contained">会員登録</Button>
                </>
              ) : (
                <>
                  <Button
                    variant="text"
                    onClick={() => {
                      setDrawerState(true);
                    }}
                  >
                    <MenuIcon />
                  </Button>
                  <Drawer
                    anchor="left"
                    open={isOpenDrawer}
                    onClose={() => {
                      setDrawerState(false);
                    }}
                  >
                    {/* <DrawerContents></DrawerContents> */}
                    <List>
                      <ListItem>
                        <ListItemButton>上越市に移住したい</ListItemButton>
                      </ListItem>
                      <ListItem>
                        <ListItemButton>上越市を紹介したい</ListItemButton>
                      </ListItem>
                    </List>
                    <Divider />
                    <List>
                      <ListItem>
                        <ListItemButton>サインイン</ListItemButton>
                      </ListItem>
                      <ListItem>
                        <ListItemButton>会員登録</ListItemButton>
                      </ListItem>
                    </List>
                  </Drawer>
                </>
              )}
            </Stack>
          </Stack>
        </header>
      </Container>
      <hr />
      <Container maxWidth="lg">
        <main>
          <div>
            <Stack
              direction="column"
              alignItems="center"
              justifyContent="center"
              sx={{ marginBottom: 5 }}
            >
              <h2>大自然に育まれた城下町 上越市</h2>
              {/* <Image
                src="/images/landing_image.png"
                width={1024}
                height={418}
              /> */}
              <Box
                component="img"
                sx={{
                  width: '80%',
                  backgroundColor: 'white',
                }}
                src="/images/landing_org.png"
              />
            </Stack>
            <Grid
              container
              direction="row"
              alignItems="center"
              justifyContent="center"
              spacing={{ xs: 2, md: 3 }}
              columns={{ xs: 4, sm: 4, md: 12 }}
            >
              <Grid item xs="auto">
                <Button
                  variant="contained"
                  sx={{ width: 300, height: 50, fontSize: 18 }}
                >
                  今すぐ会員登録する
                </Button>
              </Grid>
              <Grid item xs="auto">
                <Button
                  variant="contained"
                  sx={{ width: 300, height: 50, fontSize: 18 }}
                  color="success"
                >
                  移住を検討したい方はこちら
                </Button>
              </Grid>
              <Grid item xs="auto">
                <Button
                  variant="contained"
                  sx={{ width: 300, height: 50, fontSize: 18 }}
                  color="warning"
                >
                  上越市を紹介したい方はこちら
                </Button>
              </Grid>
            </Grid>
            <Stack
              direction="column"
              alignItems="center"
              justifyContent="center"
            >
              <h2>お住まい探しはこちら</h2>
              <Grid
                container
                direction="row"
                alignItems="center"
                justifyContent="center"
                spacing={{ xs: 2, md: 3 }}
                columns={{ xs: 4, sm: 8, md: 12 }}
              >
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/condo_1.png"
                  />
                </Grid>
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/condo_2.png"
                  />
                </Grid>
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/condo_3.png"
                  />
                </Grid>
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/apartment_1.png"
                  ></Box>
                </Grid>
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/apartment_2.png"
                  />
                </Grid>
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/apartment_3.png"
                  />
                </Grid>
              </Grid>
            </Stack>
            <Stack
              direction="column"
              alignItems="center"
              justifyContent="center"
              sx={{ marginTop: 5 }}
            >
              <h2>お仕事探しはこちら</h2>
              <Grid
                container
                direction="row"
                alignItems="center"
                justifyContent="center"
                spacing={{ xs: 2, md: 3 }}
                columns={{ xs: 4, sm: 8, md: 12 }}
              >
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/job_1.png"
                  />
                </Grid>
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/job_2.png"
                  />
                </Grid>
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/job_3.png"
                  />
                </Grid>
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/job_4.png"
                  />
                </Grid>
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/job_5.png"
                  />
                </Grid>
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/job_6.png"
                  />
                </Grid>
              </Grid>
            </Stack>
            <Stack
              direction="column"
              alignItems="center"
              justifyContent="center"
              sx={{ marginTop: 5 }}
            >
              <h2>上越市の魅力を発見</h2>
              <Grid
                container
                direction="row"
                alignItems="center"
                justifyContent="center"
                spacing={{ xs: 2, md: 3 }}
                columns={{ xs: 4, sm: 8, md: 12 }}
              >
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/feature_1.png"
                  />
                </Grid>
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/feature_2.png"
                  />
                </Grid>
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/feature_3.png"
                  />
                </Grid>
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/feature_4.png"
                  />
                </Grid>
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/feature_5.png"
                  />
                </Grid>
                <Grid item xs="auto">
                  <Box
                    component="img"
                    sx={{
                      width: 300,
                      height: 200,
                      backgroundColor: 'primary.dark',
                    }}
                    src="/images/feature_6.png"
                  />
                </Grid>
              </Grid>
            </Stack>
          </div>
        </main>
      </Container>
      <footer>
        <Box
          sx={{
            width: '100%',
            height: 70,
            backgroundColor: 'primary.dark',
            color: 'white',
            fontSize: 12,
            marginTop: 5,
          }}
        >
          <Stack
            direction="column"
            justifyContent="center"
            alignItems="center"
            spacing={0.5}
            sx={{ height: '100%' }}
          >
            <div>Copyright &copy; あさがおドットコム All Rights Reserved.</div>
            <div>上越 愛&nbsp;&nbsp;&nbsp;あさがおドットコム</div>
          </Stack>
        </Box>
      </footer>
    </>
  );
}

// export default withAuthenticator(Home);
export default Home;
